### PR TITLE
v2.5.0

### PR DESCRIPTION
**Pull request by jannikmi**

### CODE REVIEW

**Comment by jannikmi** [comment]
@idoria75 @gpapadok @georghess @Andrewsyl any clue why the build is failing?
```
py39: commands[0]> poetry install -v
  
  [RuntimeError]
  The Poetry configuration is invalid:
    - Additional properties are not allowed ('group' was unexpected)
```

It seems like an old poetry version is being used with tox. but i pinned it in `pyproject.toml`:
```
[build-system]
requires = ["poetry-core>=1.5", "poetry>=1.4"]
```
It also seems as if tox install the correct poetry version:

```
.pkg: freeze> python -m pip freeze --all
.pkg: attrs==23.1.0,build==0.10.0,CacheControl==0.12.11,certifi==2022.12.7,cffi==1.15.1,charset-normalizer==3.1.0,cleo==2.0.1,crashtest==0.4.1,cryptography==40.0.2,distlib==0.3.6,dulwich==0.21.5,filelock==3.12.0,html5lib==1.1,idna==3.4,importlib-metadata==6.6.0,installer==0.7.0,jaraco.classes==3.2.3,jeepney==0.8.0,jsonschema==4.17.3,keyring==23.13.1,lockfile==0.12.2,more-itertools==9.1.0,msgpack==1.0.5,packaging==23.1,pexpect==4.8.0,pip==23.1.2,pkginfo==1.9.6,platformdirs==2.6.2,poetry==1.4.2,poetry-core==1.5.2,poetry-plugin-export==1.3.1,ptyprocess==0.7.0,pycparser==2.21,pyproject_hooks==1.0.0,pyrsistent==0.19.3,rapidfuzz==2.15.1,requests==2.29.0,requests-toolbelt==0.10.1,SecretStorage==3.3.3,setuptools==67.7.2,shellingham==1.5.0.post1,six==1.16.0,tomli==2.0.1,tomlkit==0.11.8,trove-classifiers==2023.5.2,urllib3==1.26.15,virtualenv==20.21.1,webencodings==0.5.1,wheel==0.40.0,zipp==3.15.0
```

**Comment by gpapadok** [comment]
Not sure if that helps but after playing around with pip trying to install poetry manually I bumped into these errors:
```
$ pip install poetry

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tox 4.5.1 requires platformdirs>=3.2, but you have platformdirs 2.6.2 which is incompatible.
```
```
$ pip install platformdirs==3.5

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
poetry 1.4.2 requires platformdirs<3.0.0,>=2.5.2, but you have platformdirs 3.5.0 which is incompatible.
```
Upgrading tox to latest and poetry to >=1.4 causes a dependency conflict on platformdirs.
Reverting tox to 3.24.4 worked fine.

**Comment by jannikmi** [comment]
Strange locally I have:
```
platformdirs                  3.5.0
poetry                        1.4.2
poetry-core                   1.5.2
tox                           4.5.1

```

**Comment by jannikmi** [comment]
@gpapadok thanks. pinning `tox==3.24.3` worked

**Pull request merged**
